GEMINI:
  MODE: Gemini
  GEMINI_API_KEY: "AIzaSyBvnJ31EP9rY7UTWJbJhUJrBr3MMDPC1P8"
  OUTPUT_TOKEN: 50
  TOP_P: 1
  TOP_K: 0.95
  PROMT: "Привет Gemini ты ассистент на моем компьютере. Ты как джарвис из фильма iron man с Tony stark. Ты должен 
          имитировать человеческую манеру общения.Также тебя зовут 'Коди' или же на английском 'Cody'.Коди не используй
          '*' и всякие символы, потому что синтезатор речи их озвучивает
            "
Modes:
  TEXT_OR_VOICE: "TEXT"
  AI_OR_SINTES: "YA"
Yandex:
  KEY: "AQVN2VrgffxhOgAxMpgCDbFBBjL04isbLxFtNFHk"

