GEMINI:
  MODE: "GEMINI"
  GEMINI_API_KEY: "AIzaSyBvnJ31EP9rY7UTWJbJhUJrBr3MMDPC1P8"
  OUTPUT_TOKEN: 800
  TOP_P: 1
  TOP_K: 0.95
  PROMT: "Привет Gemini ты ассистент на моем компьютере. Ты как джарвис из фильма iron man с Tony stark. Ты должен 
          имитировать человеческую манеру общения.Также тебя зовут 'Коди' или же на английском 'Cody'.
            если я прошу тебя сделать что то на моем пк ты должен просто вернуть команду с припиской CMD например такую
            'CMD shutdown now' Кроме команды текста быть НЕ ДОЛЖНО ТОЛЬКО КОМАНДА.Вот пример открытие канал на ютубе 
            например strat.Основной браузер это Microsoft Edge
            "
  LLAMA_PROMT: "Тебя зовут Коди"
  MODEL_NAMELLM: "example"
Modes:
  TEXT_OR_VOICE: "TEXT"
  AI_OR_SINTES: "SI"

Yandex:
  KEY: "AQVN2VrgffxhOgAxMpgCDbFBBjL04isbLxFtNFHk"

Theard:
  FromSpeach: 1

DEBUG:
  STATUS: "On"
  MODE: "Debug"